In [1]:
import pandas as pd
import pathlib
import os

In [2]:
df1 = pd.read_csv('../dataset/xeno_canto_bird_songs.tsv', sep='\t', index_col=False)
df2 = pd.read_csv('../dataset/european_country.tsv', sep='\t')
df = pd.merge(df1, df2, how='inner', on=['countryCode'])

In [3]:
df[:3]

,gbifID,datasetKey,occurrenceID,kingdom,phylum,class,order,family,genus,species,...,dateIdentified,license,rightsHolder,recordedBy,typeStatus,establishmentMeans,lastInterpreted,mediaType,issue,country
0,1934871148,b1047888-ae52-4179-9dd5-5448ea342a24,http://data.biodiversitydata.nl/xeno-canto/obs...,Animalia,Chordata,Aves,Passeriformes,Motacillidae,Anthus,Anthus trivialis,...,NaN,CC_BY_NC_4_0,Niels Krabbe,Niels Krabbe,NaN,NaN,2018-11-14T20:22:03.559Z,SOUND;STILLIMAGE,NaN,Denmark
1,1934871176,b1047888-ae52-4179-9dd5-5448ea342a24,http://data.biodiversitydata.nl/xeno-canto/obs...,Animalia,Chordata,Aves,Passeriformes,Motacillidae,Motacilla,Motacilla flava,...,NaN,CC_BY_NC_4_0,Niels Krabbe,Niels Krabbe,NaN,NaN,2018-11-14T20:22:06.271Z,SOUND;STILLIMAGE,NaN,Denmark
2,1934871178,b1047888-ae52-4179-9dd5-5448ea342a24,http://data.biodiversitydata.nl/xeno-canto/obs...,Animalia,Chordata,Aves,Passeriformes,Locustellidae,Locustella,Locustella naevia,...,NaN,CC_BY_NC_4_0,Niels Krabbe,Niels Krabbe,NaN,NaN,2018-11-14T20:22:00.949Z,SOUND;STILLIMAGE,NaN,Denmark

In [4]:
df['gbifID'].count()

32726

In [5]:
df.columns.values

array(['gbifID', 'datasetKey', 'occurrenceID', 'kingdom', 'phylum',
       'class', 'order', 'family', 'genus', 'species',
       'infraspecificEpithet', 'taxonRank', 'scientificName',
       'countryCode', 'locality', 'publishingOrgKey', 'decimalLatitude',
       'decimalLongitude', 'coordinateUncertaintyInMeters',
       'coordinatePrecision', 'elevation', 'elevationAccuracy', 'depth',
       'depthAccuracy', 'eventDate', 'day', 'month', 'year', 'taxonKey',
       'speciesKey', 'basisOfRecord', 'institutionCode', 'collectionCode',
       'catalogNumber', 'recordNumber', 'identifiedBy', 'dateIdentified',
       'license', 'rightsHolder', 'recordedBy', 'typeStatus',
       'establishmentMeans', 'lastInterpreted', 'mediaType', 'issue',
       'country'], dtype=object)

In [6]:
df = df.drop(['datasetKey', 'occurrenceID', 'kingdom', 'phylum',
         'class', 'order', 'family', 'genus', 'infraspecificEpithet',
         'taxonRank', 'scientificName', 'countryCode',
         'locality', 'publishingOrgKey', 'decimalLatitude',
         'decimalLongitude', 'coordinateUncertaintyInMeters',
         'coordinatePrecision', 'elevation', 'elevationAccuracy', 'depth',
         'depthAccuracy', 'eventDate', 'day', 'month', 'year', 'taxonKey',
         'speciesKey', 'basisOfRecord', 'institutionCode', 'collectionCode',
         'catalogNumber', 'recordNumber', 'identifiedBy', 'dateIdentified',
         'license', 'rightsHolder', 'recordedBy', 'typeStatus',
         'establishmentMeans', 'lastInterpreted', 'mediaType', 'issue'], axis=1)

In [7]:
df

           gbifID                     species  country
0      1934871148            Anthus trivialis  Denmark
1      1934871176             Motacilla flava  Denmark
2      1934871178           Locustella naevia  Denmark
3      1934871180            Luscinia svecica  Denmark
4      1934871184           Locustella naevia  Denmark
5      1934871186            Poecile montanus  Denmark
6      1934871634          Prunella modularis  Denmark
7      1934871675           Linaria cannabina  Denmark
8      1934888041          Bucephala clangula  Denmark
9      1934894130       Carpodacus erythrinus  Denmark
10     1934894165             Passer montanus  Denmark
11     1934929388  Acrocephalus schoenobaenus  Denmark
12     1934929430      Acrocephalus palustris  Denmark
13     1934929472      Acrocephalus palustris  Denmark
14     1934929478      Acrocephalus palustris  Denmark
15     1934929547  Acrocephalus schoenobaenus  Denmark
16     1934929567      Acrocephalus palustris  Denmark
17     1934929588         Emberiza citrinella  Denmark
18     1934932600                Larus fuscus  Denmark
19     1934932629             Porzana porzana  Denmark
20     1934932643           Corvus frugilegus  Denmark
21     1934932645           Panurus biarmicus  Denmark
22     1934932646          Botaurus stellaris  Denmark
23     1934932670              Periparus ater  Denmark
24     1934932681               Turdus merula  Denmark
25     1934932687           Charadrius dubius  Denmark
26     1934932692                   Crex crex  Denmark
27     1934932720              Sterna hirundo  Denmark
28     1934932721               Columba oenas  Denmark
29     1934932728           Pyrrhula pyrrhula  Denmark
...           ...                         ...      ...
32696  1935002963               Anas penelope  Iceland
32697  1935002964                Lagopus muta  Iceland
32698  1935002965        Anser brachyrhynchus  Iceland
32699  1935002966          Fulmarus glacialis  Iceland
32700  1935002968             Aythya fuligula  Iceland
32701  1935002971         Bucephala islandica  Iceland
32702  1935002973         Bucephala islandica  Iceland
32703  1935002974       Haematopus ostralegus  Iceland
32704  1935002977               Aythya marila  Iceland
32705  1935002978   Histrionicus histrionicus  Iceland
32706  1935002980               Limosa limosa  Iceland
32707  1935002985                 Gavia immer  Iceland
32708  1935002988              Tringa totanus  Iceland
32709  1935002996               Limosa limosa  Iceland
32710  1935002997               Anas penelope  Iceland
32711  1935003003              Turdus iliacus  Iceland
32712  1935003004                 Anser anser  Iceland
32713  1935003005              Tringa totanus  Iceland
32714  1935003007           Numenius phaeopus  Iceland
32715  1935003009          Fulmarus glacialis  Iceland
32716  1935003017       Plectrophenax nivalis  Iceland
32717  1935003021              Gavia stellata  Iceland
32718  1935003024          Fulmarus glacialis  Iceland
32719  1935003029               Limosa limosa  Iceland
32720  1935003030   Histrionicus histrionicus  Iceland
32721  1935003031              Turdus iliacus  Iceland
32722  1935003051        Charadrius hiaticula  Iceland
32723  1935003056        Anser brachyrhynchus  Iceland
32724  1935003085            Podiceps auritus  Iceland
32725  1935006366           Clangula hyemalis  Iceland

[32726 rows x 3 columns]

In [8]:
files_to_remove = df[df.species.isnull()]['gbifID']

In [9]:
for file in files_to_remove:
    path = "../dataset/sound/{}.mp3".format(file)
    if os.path.exists(path):
          os.remove(path)

In [10]:
files = [f.stem for f in pathlib.Path('../dataset/sound/').glob('*.mp3')]

In [11]:
df = df[~df.species.isnull()]
df

           gbifID                     species  country
0      1934871148            Anthus trivialis  Denmark
1      1934871176             Motacilla flava  Denmark
2      1934871178           Locustella naevia  Denmark
3      1934871180            Luscinia svecica  Denmark
4      1934871184           Locustella naevia  Denmark
5      1934871186            Poecile montanus  Denmark
6      1934871634          Prunella modularis  Denmark
7      1934871675           Linaria cannabina  Denmark
8      1934888041          Bucephala clangula  Denmark
9      1934894130       Carpodacus erythrinus  Denmark
10     1934894165             Passer montanus  Denmark
11     1934929388  Acrocephalus schoenobaenus  Denmark
12     1934929430      Acrocephalus palustris  Denmark
13     1934929472      Acrocephalus palustris  Denmark
14     1934929478      Acrocephalus palustris  Denmark
15     1934929547  Acrocephalus schoenobaenus  Denmark
16     1934929567      Acrocephalus palustris  Denmark
17     1934929588         Emberiza citrinella  Denmark
18     1934932600                Larus fuscus  Denmark
19     1934932629             Porzana porzana  Denmark
20     1934932643           Corvus frugilegus  Denmark
21     1934932645           Panurus biarmicus  Denmark
22     1934932646          Botaurus stellaris  Denmark
23     1934932670              Periparus ater  Denmark
24     1934932681               Turdus merula  Denmark
25     1934932687           Charadrius dubius  Denmark
26     1934932692                   Crex crex  Denmark
27     1934932720              Sterna hirundo  Denmark
28     1934932721               Columba oenas  Denmark
29     1934932728           Pyrrhula pyrrhula  Denmark
...           ...                         ...      ...
32696  1935002963               Anas penelope  Iceland
32697  1935002964                Lagopus muta  Iceland
32698  1935002965        Anser brachyrhynchus  Iceland
32699  1935002966          Fulmarus glacialis  Iceland
32700  1935002968             Aythya fuligula  Iceland
32701  1935002971         Bucephala islandica  Iceland
32702  1935002973         Bucephala islandica  Iceland
32703  1935002974       Haematopus ostralegus  Iceland
32704  1935002977               Aythya marila  Iceland
32705  1935002978   Histrionicus histrionicus  Iceland
32706  1935002980               Limosa limosa  Iceland
32707  1935002985                 Gavia immer  Iceland
32708  1935002988              Tringa totanus  Iceland
32709  1935002996               Limosa limosa  Iceland
32710  1935002997               Anas penelope  Iceland
32711  1935003003              Turdus iliacus  Iceland
32712  1935003004                 Anser anser  Iceland
32713  1935003005              Tringa totanus  Iceland
32714  1935003007           Numenius phaeopus  Iceland
32715  1935003009          Fulmarus glacialis  Iceland
32716  1935003017       Plectrophenax nivalis  Iceland
32717  1935003021              Gavia stellata  Iceland
32718  1935003024          Fulmarus glacialis  Iceland
32719  1935003029               Limosa limosa  Iceland
32720  1935003030   Histrionicus histrionicus  Iceland
32721  1935003031              Turdus iliacus  Iceland
32722  1935003051        Charadrius hiaticula  Iceland
32723  1935003056        Anser brachyrhynchus  Iceland
32724  1935003085            Podiceps auritus  Iceland
32725  1935006366           Clangula hyemalis  Iceland

[32370 rows x 3 columns]

In [12]:
len(files)

32369

In [13]:
df[~df.gbifID.isin(files)]

           gbifID             species country
11312  1934959574  Erithacus rubecula  Russia

In [14]:
df = df.drop([9770])

In [15]:
df

           gbifID                     species  country
0      1934871148            Anthus trivialis  Denmark
1      1934871176             Motacilla flava  Denmark
2      1934871178           Locustella naevia  Denmark
3      1934871180            Luscinia svecica  Denmark
4      1934871184           Locustella naevia  Denmark
5      1934871186            Poecile montanus  Denmark
6      1934871634          Prunella modularis  Denmark
7      1934871675           Linaria cannabina  Denmark
8      1934888041          Bucephala clangula  Denmark
9      1934894130       Carpodacus erythrinus  Denmark
10     1934894165             Passer montanus  Denmark
11     1934929388  Acrocephalus schoenobaenus  Denmark
12     1934929430      Acrocephalus palustris  Denmark
13     1934929472      Acrocephalus palustris  Denmark
14     1934929478      Acrocephalus palustris  Denmark
15     1934929547  Acrocephalus schoenobaenus  Denmark
16     1934929567      Acrocephalus palustris  Denmark
17     1934929588         Emberiza citrinella  Denmark
18     1934932600                Larus fuscus  Denmark
19     1934932629             Porzana porzana  Denmark
20     1934932643           Corvus frugilegus  Denmark
21     1934932645           Panurus biarmicus  Denmark
22     1934932646          Botaurus stellaris  Denmark
23     1934932670              Periparus ater  Denmark
24     1934932681               Turdus merula  Denmark
25     1934932687           Charadrius dubius  Denmark
26     1934932692                   Crex crex  Denmark
27     1934932720              Sterna hirundo  Denmark
28     1934932721               Columba oenas  Denmark
29     1934932728           Pyrrhula pyrrhula  Denmark
...           ...                         ...      ...
32696  1935002963               Anas penelope  Iceland
32697  1935002964                Lagopus muta  Iceland
32698  1935002965        Anser brachyrhynchus  Iceland
32699  1935002966          Fulmarus glacialis  Iceland
32700  1935002968             Aythya fuligula  Iceland
32701  1935002971         Bucephala islandica  Iceland
32702  1935002973         Bucephala islandica  Iceland
32703  1935002974       Haematopus ostralegus  Iceland
32704  1935002977               Aythya marila  Iceland
32705  1935002978   Histrionicus histrionicus  Iceland
32706  1935002980               Limosa limosa  Iceland
32707  1935002985                 Gavia immer  Iceland
32708  1935002988              Tringa totanus  Iceland
32709  1935002996               Limosa limosa  Iceland
32710  1935002997               Anas penelope  Iceland
32711  1935003003              Turdus iliacus  Iceland
32712  1935003004                 Anser anser  Iceland
32713  1935003005              Tringa totanus  Iceland
32714  1935003007           Numenius phaeopus  Iceland
32715  1935003009          Fulmarus glacialis  Iceland
32716  1935003017       Plectrophenax nivalis  Iceland
32717  1935003021              Gavia stellata  Iceland
32718  1935003024          Fulmarus glacialis  Iceland
32719  1935003029               Limosa limosa  Iceland
32720  1935003030   Histrionicus histrionicus  Iceland
32721  1935003031              Turdus iliacus  Iceland
32722  1935003051        Charadrius hiaticula  Iceland
32723  1935003056        Anser brachyrhynchus  Iceland
32724  1935003085            Podiceps auritus  Iceland
32725  1935006366           Clangula hyemalis  Iceland

[32369 rows x 3 columns]

In [16]:
set(df.species.values)

{'Acanthis flammea',
 'Acanthis hornemanni',
 'Accipiter badius',
 'Accipiter gentilis',
 'Accipiter gularis',
 'Accipiter nisus',
 'Accipiter soloensis',
 'Acridotheres tristis',
 'Acrocephalus agricola',
 'Acrocephalus arundinaceus',
 'Acrocephalus bistrigiceps',
 'Acrocephalus dumetorum',
 'Acrocephalus melanopogon',
 'Acrocephalus orientalis',
 'Acrocephalus paludicola',
 'Acrocephalus palustris',
 'Acrocephalus schoenobaenus',
 'Acrocephalus scirpaceus',
 'Actitis hypoleucos',
 'Aegithalos caudatus',
 'Aegolius funereus',
 'Aegypius monachus',
 'Agropsar philippensis',
 'Agropsar sturninus',
 'Aix galericulata',
 'Alauda arvensis',
 'Alca torda',
 'Alcedo atthis',
 'Alectoris barbara',
 'Alectoris chukar',
 'Alectoris graeca',
 'Alectoris rufa',
 'Alopochen aegyptiaca',
 'Amaurornis phoenicurus',
 'Anas acuta',
 'Anas clypeata',
 'Anas crecca',
 'Anas falcata',
 'Anas formosa',
 'Anas penelope',
 'Anas platyrhynchos',
 'Anas poecilorhyncha',
 'Anas querquedula',
 'Anas strepera',
 'Anser albifrons',
 'Anser anser',
 'Anser brachyrhynchus',
 'Anser cygnoides',
 'Anser erythropus',
 'Anser fabalis',
 'Anser indicus',
 'Anser serrirostris',
 'Anthropoides virgo',
 'Anthus berthelotii',
 'Anthus campestris',
 'Anthus cervinus',
 'Anthus godlewskii',
 'Anthus gustavi',
 'Anthus hodgsoni',
 'Anthus petrosus',
 'Anthus pratensis',
 'Anthus richardi',
 'Anthus rubescens',
 'Anthus spinoletta',
 'Anthus trivialis',
 'Aptenodytes patagonicus',
 'Apus apus',
 'Apus pacificus',
 'Apus pallidus',
 'Apus unicolor',
 'Aquila adalberti',
 'Ardea alba',
 'Ardea cinerea',
 'Ardea purpurea',
 'Ardeola bacchus',
 'Ardeola ralloides',
 'Arenaria interpres',
 'Asio flammeus',
 'Asio otus',
 'Athene noctua',
 'Aythya ferina',
 'Aythya fuligula',
 'Aythya marila',
 'Balearica regulorum',
 'Bombycilla garrulus',
 'Botaurus stellaris',
 'Branta bernicla',
 'Branta canadensis',
 'Branta leucopsis',
 'Bubo bubo',
 'Bubo scandiacus',
 'Bubulcus coromandus',
 'Bubulcus ibis',
 'Bucanetes githagineus',
 'Bucanetes mongolicus',
 'Bucephala clangula',
 'Bucephala islandica',
 'Burhinus oedicnemus',
 'Butastur indicus',
 'Buteo buteo',
 'Buteo japonicus',
 'Buteo lagopus',
 'Buteo rufinus',
 'Butorides striata',
 'Calandrella brachydactyla',
 'Calandrella cheleensis',
 'Calandrella rufescens',
 'Calcarius lapponicus',
 'Calidris acuminata',
 'Calidris alba',
 'Calidris alpina',
 'Calidris canutus',
 'Calidris ferruginea',
 'Calidris maritima',
 'Calidris melanotos',
 'Calidris minuta',
 'Calidris ruficollis',
 'Calidris subminuta',
 'Calidris temminckii',
 'Calonectris borealis',
 'Capella media',
 'Caprimulgus europaeus',
 'Caprimulgus ruficollis',
 'Carduelis carduelis',
 'Carduelis citrinella',
 'Carpodacus erythrinus',
 'Carpodacus rhodochlamys',
 'Carpodacus sibiricus',
 'Cecropis daurica',
 'Certhia brachydactyla',
 'Certhia familiaris',
 'Cettia cetti',
 'Charadrius alexandrinus',
 'Charadrius dubius',
 'Charadrius hiaticula',
 'Charadrius morinellus',
 'Charadrius placidus',
 'Chersophilus duponti',
 'Chlidonias hybrida',
 'Chlidonias leucopterus',
 'Chlidonias niger',
 'Chloris chloris',
 'Chloris sinica',
 'Chroicocephalus genei',
 'Chrysolophus amherstiae',
 'Ciconia ciconia',
 'Cinclodes antarcticus',
 'Cinclus cinclus',
 'Circus aeruginosus',
 'Circus macrourus',
 'Circus pygargus',
 'Cisticola juncidis',
 'Clamator glandarius',
 'Clangula hyemalis',
 'Coccothraustes coccothraustes',
 'Coloeus monedula',
 'Columba bollii',
 'Columba livia',
 'Columba oenas',
 'Columba palumbus',
 'Columba rupestris',
 'Coracias garrulus',
 'Corvus corax',
 'Corvus cornix',
 'Corvus corone',
 'Corvus frugilegus',
 'Corvus macrorhynchos',
 'Coturnix coturnix',
 'Coturnix japonica',
 'Crex crex',
 'Cuculus canorus',
 'Cuculus hyperythrus',
 'Cuculus micropterus',
 'Cuculus optatus',
 'Cuculus poliocephalus',
 'Cuculus sparverioides',
 'Cyanistes caeruleus',
 'Cyanistes cyanus',
 'Cyanistes teneriffae',
 'Cyanopica cooki',
 'Cyanoptila cyanomelana',
 'Cygnus columbianus',
 'Cygnus cygnus',
 'Cygnus olor',
 'Delichon urbicum',
 'Dendrocopos kizuki',
 'Dendrocopos leucopterus',
 'Dendrocopos leucotos',
 'Dendrocopos major',
 'Dendrocopos medius',
 'Dendrocopos minor',
 'Dendronanthus indicus',
 'Dryocopus martius',
 'Egretta garzetta',
 'Emberiza bruniceps',
 'Emberiza calandra',
 'Emberiza cia',
 'Emberiza cioides',
 'Emberiza cirlus',
 'Emberiza citrinella',
 'Emberiza elegans',
 'Emberiza fucata',
 'Emberiza hortulana',
 'Emberiza leucocephalos',
 'Emberiza pallasi',
 'Emberiza pusilla',
 'Emberiza rustica',
 'Emberiza schoeniclus',
 'Emberiza spodocephala',
 'Emberiza stewarti',
 'Emberiza tristrami',
 'Emberiza yessoensis',
 'Eremophila alpestris',
 'Erithacus rubecula',
 'Erythropygia galactotes',
 'Estrilda astrild',
 'Eudyptes chrysocome',
 'Euplectes afer',
 'Eurystomus orientalis',
 'Falco amurensis',
 'Falco cherrug',
 'Falco columbarius',
 'Falco naumanni',
 'Falco peregrinus',
 'Falco subbuteo',
 'Falco tinnunculus',
 'Falco vespertinus',
 'Ficedula albicilla',
 'Ficedula albicollis',
 'Ficedula hypoleuca',
 'Ficedula mugimaki',
 'Ficedula parva',
 'Ficedula zanthopygia',
 'Fratercula arctica',
 'Fringilla coelebs',
 'Fringilla montifringilla',
 'Fringilla teydea',
 'Fulica atra',
 'Fulica cristata',
 'Fulmarus glacialis',
 'Galerida cristata',
 'Galerida theklae',
 'Gallinago gallinago',
 'Gallinago stenura',
 'Gallinula chloropus',
 'Garrulus glandarius',
 'Gavia arctica',
 'Gavia immer',
 'Gavia stellata',
 'Geokichla sibirica',
 'Glareola nordmanni',
 'Glareola pratincola',
 'Glaucidium cuculoides',
 'Glaucidium passerinum',
 'Grus grus',
 'Grus monacha',
 'Gyps fulvus',
 'Haematopus ostralegus',
 'Haliaeetus albicilla',
 'Hieraaetus pennatus',
 'Himantopus himantopus',
 'Hippolais icterina',
 'Hippolais polyglotta',
 'Hirundo rustica',
 'Histrionicus histrionicus',
 'Horornis borealis',
 'Hydrobates pelagicus',
 'Hydroprogne caspia',
 'Hypopicus hyperythrus',
 'Hypsipetes amaurotis',
 'Ichthyaetus audouinii',
 'Ichthyaetus ichthyaetus',
 'Ichthyaetus melanocephalus',
 'Iduna aedon',
 'Iduna caligata',
 'Iduna pallida',
 'Iduna rama',
 'Ixobrychus eurhythmus',
 'Ixobrychus minutus',
 'Ixobrychus sinensis',
 'Junco hyemalis',
 'Jynx torquilla',
 'Lagopus lagopus',
 'Lagopus muta',
 'Lanius collurio',
 'Lanius cristatus',
 'Lanius excubitor',
 'Lanius isabellinus',
 'Lanius meridionalis',
 'Lanius minor',
 'Lanius pallidirostris',
 'Lanius phoenicuroides',
 'Lanius senator',
 'Lanius sphenocercus',
 'Lanius tigrinus',
 'Larus argentatus',
 'Larus cachinnans',
 'Larus canus',
 'Larus crassirostris',
 'Larus fuscus',
 'Larus glaucoides',
 'Larus marinus',
 'Larus michahellis',
 'Larus minutus',
 'Larus ridibundus',
 'Larus schistisagus',
 'Larus vegae',
 'Leucosticte brandti',
 'Leucosticte nemoricola',
 'Limicola falcinellus',
 'Limnodromus semipalmatus',
 'Limosa lapponica',
 'Limosa limosa',
 'Linaria cannabina',
 'Linaria flavirostris',
 'Locustella certhiola',
 'Locustella fasciolata',
 'Locustella fluviatilis',
 'Locustella lanceolata',
 'Locustella luscinioides',
 'Locustella naevia',
 'Locustella pleskei',
 'Locustella pryeri',
 'Locustella tacsanowskia',
 'Lophophanes cristatus',
 'Loxia curvirostra',
 'Loxia leucoptera',
 'Loxia pytyopsittacus',
 'Lullula arborea',
 'Luscinia calliope',
 'Luscinia cyane',
 'Luscinia luscinia',
 'Luscinia megarhynchos',
 'Luscinia sibilans',
 'Luscinia svecica',
 'Lymnocryptes minimus',
 'Lyrurus tetrix',
 'Macronectes halli',
 'Marmaronetta angustirostris',
 'Melanitta fusca',
 'Melanitta nigra',
 'Melanocorypha bimaculata',
 'Melanocorypha calandra',
 'Melanocorypha leucoptera',
 'Melanocorypha yeltoniensis',
 'Mergus merganser',
 'Mergus serrator',
 'Merops apiaster',
 'Merops nubicus',
 'Merops persicus',
 'Milvus migrans',
 'Milvus milvus',
 'Monticola gularis',
 'Monticola saxatilis',
 'Monticola solitarius',
 'Montifringilla nivalis',
 'Morus bassanus',
 'Motacilla alba',
 'Motacilla cinerea',
 'Motacilla citreola',
 'Motacilla flava',
 'Motacilla tschutschensis',
 'Muscicapa dauurica',
 'Muscicapa griseisticta',
 'Muscicapa latirostris',
 'Myiopsitta monachus',
 'Myophonus caeruleus',
 'Netta rufina',
 'Ninox scutulata',
 'Nisaetus nipalensis',
 'Nucifraga caryocatactes',
 'Numenius arquata',
 'Numenius madagascariensis',
 'Numenius phaeopus',
 'Nycticorax nycticorax',
 'Nymphicus hollandicus',
 'Oceanodroma castro',
 'Oenanthe deserti',
 'Oenanthe hispanica',
 'Oenanthe isabellina',
 'Oenanthe oenanthe',
 'Oenanthe pleschanka',
 'Oriolus kundoo',
 'Oriolus oriolus',
 'Otus bakkamoena',
 'Otus brucei',
 'Otus scops',
 'Otus semitorques',
 'Otus sunia',
 'Pandion haliaetus',
 'Panurus biarmicus',
 'Paradoxornis polivanovi',
 'Parus major',
 'Parus minor',
 'Passer domesticus',
 'Passer hispaniolensis',
 'Passer italiae',
 'Passer montanus',
 'Passer rutilans',
 'Pastor roseus',
 'Perdix perdix',
 'Pericrocotus divaricatus',
 'Periparus ater',
 'Periparus venustulus',
 'Perisoreus infaustus',
 'Pernis apivorus',
 'Petronia petronia',
 'Phalacrocorax carbo',
 'Phalaropus lobatus',
 'Phalcoboenus australis',
 'Phasianus colchicus',
 'Philomachus pugnax',
 'Phoebetria palpebrata',
 'Phoenicopterus roseus',
 'Phoenicurus auroreus',
 'Phoenicurus erythrogastrus',
 'Phoenicurus ochruros',
 'Phoenicurus phoenicurus',
 'Phylloscopus bonelli',
 'Phylloscopus borealis',
 'Phylloscopus canariensis',
 'Phylloscopus collybita',
 'Phylloscopus coronatus',
 'Phylloscopus examinandus',
 'Phylloscopus fuscatus',
 'Phylloscopus griseolus',
 'Phylloscopus humei',
 'Phylloscopus ibericus',
 'Phylloscopus inornatus',
 'Phylloscopus nitidus',
 'Phylloscopus plumbeitarsus',
 'Phylloscopus proregulus',
 'Phylloscopus schwarzi',
 'Phylloscopus sibillatrix',
 'Phylloscopus sindianus',
 'Phylloscopus tenellipes',
 'Phylloscopus trochiloides',
 'Phylloscopus trochilus',
 'Pica pica',
 'Picoides tridactylus',
 'Picus canus',
 'Picus viridis',
 'Pinicola enucleator',
 'Platalea leucorodia',
 'Plectrophenax nivalis',
 'Plegadis falcinellus',
 'Pluvialis apricaria',
 'Pluvialis squatarola',
 'Podiceps auritus',
 'Podiceps cristatus',
 'Podiceps grisegena',
 'Podiceps nigricollis',
 'Poecile cinctus',
 'Poecile lugubris',
 'Poecile montanus',
 'Poecile palustris',
 'Porphyrio porphyrio',
 'Porzana fusca',
 'Porzana parva',
 'Porzana paykullii',
 'Porzana porzana',
 'Porzana pusilla',
 'Prunella collaris',
 'Prunella fulvescens',
 'Prunella modularis',
 'Prunella montanella',
 'Psittacula eupatria',
 'Psittacula krameri',
 'Pterocles alchata',
 'Pterocles orientalis',
 'Ptyonoprogne rupestris',
 'Puffinus puffinus',
 'Pyrrhocorax graculus',
 'Pyrrhocorax pyrrhocorax',
 'Pyrrhula pyrrhula',
 'Rallus aquaticus',
 'Rallus indicus',
 'Recurvirostra avosetta',
 'Regulus ignicapilla',
 'Regulus madeirensis',
 'Regulus regulus',
 'Remiz consobrinus',
 'Remiz coronatus',
 'Remiz pendulinus',
 'Rhodospiza obsoleta',
 'Rhodostethia rosea',
 'Riparia riparia',
 'Rissa tridactyla',
 'Saxicola maurus',
 'Saxicola rubetra',
 'Saxicola rubicola',
 'Saxicola stejnegeri',
 'Saxicola tectes',
 'Scolopax rusticola',
 'Serinus canaria',
 'Serinus serinus',
 'Setophaga striata',
 'Sinosuthora webbiana',
 'Sitta europaea',
 'Sitta neumayer',
 'Sitta tephronota',
 'Sitta villosa',
 'Somateria mollissima',
 'Spinus spinus',
 'Spizelloides arborea',
 'Spodiopsar cineraceus',
 'Spodiopsar sericeus',
 'Stercorarius antarcticus',
 'Stercorarius longicaudus',
 'Sterna hirundo',
 'Sterna nilotica',
 'Sterna paradisaea',
 'Sternula albifrons',
 'Streptopelia decaocto',
 'Streptopelia orientalis',
 'Streptopelia turtur',
 'Strix aluco',
 'Strix nebulosa',
 'Strix uralensis',
 'Sturnus unicolor',
 'Sturnus vulgaris',
 'Surnia ulula',
 'Sylvia althaea',
 'Sylvia atricapilla',
 'Sylvia balearica',
 'Sylvia borin',
 'Sylvia cantillans',
 'Sylvia communis',
 'Sylvia conspicillata',
 'Sylvia crassirostris',
 'Sylvia curruca',
 'Sylvia hortensis',
 'Sylvia melanocephala',
 'Sylvia mystacea',
 'Sylvia nana',
 'Sylvia nisoria',
 'Sylvia subalpina',
 'Sylvia undata',
 'Syrrhaptes paradoxus',
 'Tachybaptus ruficollis',
 'Tachyeres brachypterus',
 'Tadorna ferruginea',
 'Tadorna tadorna',
 'Tarsiger cyanurus',
 'Terpsiphone incei',
 'Tetrao urogallus',
 'Tetrastes bonasia',
 'Tetrax tetrax',
 'Thalassarche melanophris',
 'Thalasseus sandvicensis',
 'Tichodroma muraria',
 'Treron sieboldii',
 'Tringa erythropus',
 'Tringa glareola',
 'Tringa nebularia',
 'Tringa ochropus',
 'Tringa stagnatilis',
 'Tringa totanus',
 'Troglodytes cobbi',
 'Troglodytes troglodytes',
 'Turdus atrogularis',
 'Turdus chrysolaus',
 'Turdus eunomus',
 'Turdus falcklandii',
 'Turdus hortulorum',
 'Turdus iliacus',
 'Turdus merula',
 'Turdus naumanni',
 'Turdus obscurus',
 'Turdus pallidus',
 'Turdus philomelos',
 'Turdus pilaris',
 'Turdus ruficollis',
 'Turdus torquatus',
 'Turdus viscivorus',
 'Turnix tanki',
 'Tyto alba',
 'Upupa epops',
 'Uria aalge',
 'Urosphena squameiceps',
 'Vanellus indicus',
 'Vanellus leucurus',
 'Vanellus vanellus',
 'Xenus cinereus',
 'Zoothera aurea',
 'Zosterops borbonicus',
 'Zosterops erythropleurus',
 'Zosterops olivaceus'}

In [17]:
len(set(df.species.values))

588

In [18]:
df.to_csv('../dataset/xeno_canto_bird_songs_cleaned.tsv', sep='\t', index=False)